name: my_garden_app
description: "A new Flutter project."


# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  calendar_view: ^1.2.0
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  email_validator: ^2.0.1
  equatable: ^2.0.5
  flame: ^1.26.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  flutter_sticky_header: ^0.7.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.1.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  injectable: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  mockito: ^5.4.4
  multi_bloc_builder: ^1.0.0
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
